spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Ywm@mysql36
    url: jdbc:mysql://36.41.187.107/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  context-path: /sell
